development:
  database: stories_development
  username: root
  password: root
  host: localhost
  adapter: mysql2
  encoding: utf8
test:
  database: stories_test
  username: root
  password: root
  host: localhost
  pool: 5
  timeout: 5000
  adapter: mysql2
  encoding: utf8
